name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest ruff

    - name: Verify test files exist
      run: |
        if [ -d "tests" ]; then
          echo "✅ Test folder exists"
          ls -R tests/
        else
          echo "❌ ERROR: 'tests' folder is missing!"
          exit 1
        fi
      shell: bash

    - name: Check which tests are found
      run: |
        pytest --collect-only

    - name: Run tests with pytest
      run: |
        pytest tests/ --disable-warnings || (echo "❌ Tests failed!" && exit 1)

    - name: Lint and format with Ruff
      run: |
        ruff --version
        ruff check --fix .
