name: Python CI with Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pytest and Ruff
        run: |
          pip install pytest ruff

      - name: Lint with Ruff
        run: |
          ruff --version  # Verifying installation first
          ruff check . 

      - name: Run tests with pytest
        run: |
          export PYTHONPATH=$(pwd)
          pytest --maxfail=3 --disable-warnings -v
